config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resources :lists do
    resources :tasks
  end

  resources :tags, only: [:index, :new, :create]

  put '/change', to: 'tasks#change_status'


end

app/models/list.rb
class List < ActiveRecord::Base
  validates :title, presence: true
  has_many :tasks
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many  :task_tags
  has_many  :tasks, through: :task_tags
  validates :title, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  has_many  :task_tags
  has_many  :tags, through: :task_tags
  validates :title, presence: true
  validates :start_date, presence: true
  validate :start_date_cannot_be_in_the_past,
           :due_date_cannot_be_in_the_past

  scope :current, -> { where(completed: false).where("start_date <= ?", Date.today) }
  scope :complete, -> { where(completed: true) }
  scope :future, -> { where(completed: false).where("start_date > ?", Date.today) }

  def start_date_cannot_be_in_the_past
    errors.add(:start_date, "can't be in the past") if
      !start_date.blank? && start_date < Date.today
  end

  def due_date_cannot_be_in_the_past
    errors.add(:due_date, "can't be in the past") if
      !due_date.blank? && due_date < Date.today
  end

  def update_status
    if complete?
      update(status: 'incomplete')
    else
      update(status: 'complete')
    end
  end

end

app/models/task_tag.rb
class TaskTag < ActiveRecord::Base
  belongs_to :task
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      flash[:success] = "List successfully created"
      redirect_to lists_path
    else
      flash[:danger] = "Invalid entry"
      render :new
    end
  end

  def index
    @lists = List.all
  end

  def show
    @tags = Tag.all
    @list = List.find(params[:id])
    @tasks = @list.tasks.current
    @complete_tasks = @list.tasks.complete
    @future_tasks = @list.tasks.future
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to lists_path
    else
      flash[:danger] = "Invalid entry"
      render :edit
    end
  end

  def destroy
    list = List.find(params[:id])
    list.tasks.each do |task|
      task.destroy
    end
    list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:title, :description)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
      @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:success] = "Tag successfully created"
      redirect_to tags_path
    else
      flash[:danger] = "Invalid entry"
      render :new
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:title)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  respond_to :json

  def index
    list = List.find(params[:list_id])
    @tasks = list.tasks.where(completed: false)
  end

  def show
    list = List.find(params[:list_id])
    @task = list.tasks.find(params[:id])
  end

  def new
    @tags = Tag.all
    @list = List.find(params[:list_id])
    @task = Task.new
  end

  def create
    list = List.find(params[:list_id])
    @task = list.tasks.new(task_params)
    if @task.save
      assign_tags
      flash[:notice] = "Task successfully created"
      redirect_to list_path(list)
    else
      @tags = Tag.all
        render :new
    end
  end

  def edit
    @tags = Tag.all
    list = List.find(params[:list_id])
    @task = list.tasks.find(params[:id])
  end

  def update
    list = List.find(params[:list_id])
    @task = list.tasks.find(params[:id])
    if @task.update(task_params)
      assign_tags
      redirect_to list_path(list)
    else
      @tags = Tag.all
      flash[:notice] = "Invalid entry"
      render :edit
    end
  end

  def change_status
    task = Task.find(params[:task_id])
    task.completed = params[:completed]
    if task.save
      respond_with Task.find(params[:task_id])
    else
      respond_with({errors => task.errors}, :status => 422, :location => list_path(task.list_id))
    end
  end

  private

  def task_params
    params.require(:task).permit(:title,
                                 :completed,
                                 :notes,
                                 :due_date,
                                 :start_date,
                                 :list_id
                                 )
  end

  def assign_tags
    tags = params[:task][:tag_ids].reject(&:empty?)
    tags.each do |id|
      @task.tags << Tag.find(id) unless @task.tags.include?(Tag.find(id))
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

  def check_box_checked?(task)
    task.completed == true
  end

end

app/views/home/index.html.erb
<div class="welcome"><h1>Wecome to your task management app!</h1>

  <%= link_to "Create a new list", new_list_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskManager</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render :partial => 'partials/navbar' %>

  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :class => "alert alert-#{name}" %>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/lists/edit.html.erb
<%= render :partial => 'partials/list_form' %>

app/views/lists/index.html.erb
<div class="user-header"><h1>Current Task Lists:</h1></div>
<div class="newlist"><%= link_to "Create new list", new_list_path %></div><br><br>

<ul class="list-group">
<% @lists.each do |list| %>
<li class="list-group-item"><%= link_to "#{list.title}", list_path(list) %>
<%= list.description %>
<%= link_to "Edit", edit_list_path(list) %>
<%= link_to "Delete", list_path(list), method: "delete" %>
<% end %>
</ul>

app/views/lists/new.html.erb
<%= render :partial => 'partials/list_form' %>

app/views/lists/show.html.erb
<h1><%= @list.title %> tasks: </h1>
<%= link_to "Add Task", new_list_task_path(list_id: @list.id) %>


<%= form_tag(list_path, :method => "get", class: "navbar-form", id: "search-form") do %>
  <div class="input-append">
    <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search by Title", id: "title-filter" %>
    <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search by Start Date", id: "start-date-filter" %>
    <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search by Due Date", id: "due-date-filter" %>
  </div>
<% end %>

<div id="task-tags-filter">
  Filter By:
  <button type="button" class="btn btn-default tag-button" aria-label="Left Align">all</button>
  <% @tags.each do |tag| %>
    <button type="button" class="btn btn-default tag-button" aria-label="Left Align"><%= tag.title %></button>
  <% end %>
</div>

<div id="task-table">
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Notes</th>
      <th>Start Date</th>
      <th>Due Date</th>
      <th>Tags</th>
      <th>Complete?</th>
      <th>Edit</th>
    </tr>
  </thead>
  <tbody class="tasks">
    <tr class="task"><% @tasks.each do |task| %>
      <td class="task-title"><%= task.title %></td>
      <td><%= task.notes %></td>
      <td class="start-date"><%= task.start_date %></td>
      <td class="due-date"><%= task.due_date %></td>
      <td class="task-tags"><% task.tags.each do |tag| %>
          <%= tag.title %>
          <% end %>
      </td>
      <td><a href="#" class="task-status" data-id=<%=task.id %>><%= task.completed %></a></td>
      <td><%= link_to "Edit", edit_list_task_path(id: task.id, list_id: @list.id) %></td></tr>
    <% end %>
  </tbody>
</table>
</div>

<button type="button" class="btn btn-default" aria-label="Left Align" id="future-button">View Future Tasks</button>
<button type="button" class="btn btn-default" aria-label="Left Align" id="completed-button">View Completed Tasks</button>

<div id="future-task-table" style="display: none">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Title</th>
        <th>Notes</th>
        <th>Start Date</th>
        <th>Due Date</th>
        <th>Tags</th>
        <th>Complete?</th>
        <th>Edit</th>
      </tr>
    </thead>
    <tbody class="tasks">
      <tr class="task"><% @future_tasks.each do |task| %>
        <td class="task-title"><%= task.title %></td>
        <td><%= task.notes %></td>
        <td><%= task.start_date %></td>
        <td><%= task.due_date %></td>
        <td class="task-tags"><% task.tags.each do |tag| %>
            <%= tag.title %>
            <% end %>
        </td>
        <td><a href="#" class="task-status" data-id=<%=task.id %>><%= task.completed %></a></td>
        <td><%= link_to "Edit", edit_list_task_path(id: task.id, list_id: @list.id) %></td></tr>
      <% end %>
    </tbody>
  </table>
</div>

<div id="completed-task-table" style="display: none">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Title</th>
        <th>Notes</th>
        <th>Start Date</th>
        <th>Due Date</th>
        <th>Tags</th>
        <th>Complete?</th>
        <th>Edit</th>
      </tr>
    </thead>
    <tbody class="tasks">
      <tr class="task"><% @complete_tasks.each do |task| %>
        <td class="task-title"><%= task.title %></td>
        <td><%= task.notes %></td>
        <td><%= task.start_date %></td>
        <td><%= task.due_date %></td>
        <td class="task-tags"><% task.tags.each do |tag| %>
            <%= tag.title %>
            <% end %>
        </td>
        <td><a href="#" class="task-status" data-id=<%=task.id %>><%= task.completed %></a></td>
        <td><%= link_to "Edit", edit_list_task_path(id: task.id, list_id: @list.id) %></td></tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/partials/_list_form.html.erb
<%= bootstrap_form_for(@list, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-6") do |f| %>

  <%= f.text_field :title %>
  <%= f.text_field :description %>
  <%= f.form_group do %>
    <%= f.submit "Submit" %>
  <% end %>
<% end %>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Task Manager 3.0</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "My Tags", tags_path%></li>
        <li><%= link_to "My Lists", lists_path%></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/tags/index.html.erb
<%= link_to "Create New Tag", new_tag_path %>

<h3>Your tags:</h3>
<% @tags.each do |tag| %>
  <%= tag.title %>
<% end %>

<% @tags.each do |tag| %>
  <h3><%= tag.title %></h3><br>
  <% tag.tasks.each do |task| %>
    <b>Task: </b><%= task.title %>
    <b>List: </b><%= task.list.title %><br>
  <% end %>
<% end %><br><br>

app/views/tags/new.html.erb
<%= bootstrap_form_for(@tag, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-6") do |f| %>

  <%= f.text_field :title %>
  <%= f.form_group do %>
    <%= f.submit "Submit"%>
  <% end %>
<% end %>

app/views/tasks/edit.html.erb
<%= bootstrap_form_for(@task, url: list_task_path(@task.list_id ,@task.id), method: :patch, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-6") do |f| %>

  <%= f.text_field :title %>
  <%= f.text_field :notes %>
  <%= f.form_group do %>
    <%= f.check_box :completed %>
  <% end %>
  <%= f.date_field :start_date %>
  <%= f.date_field :due_date %>
  <%= f.collection_check_boxes(:tag_ids, @tags, :id, :title) %>
  <%= f.form_group do %>
    <%= f.submit "Submit"%>
  <% end %>
<% end %>

app/views/tasks/new.html.erb
<%= bootstrap_form_for(@task, url: list_tasks_path, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-6") do |f| %>

  <%= f.text_field :title %>
  <%= f.text_field :notes %>
  <%= f.form_group do %>
    <%= f.check_box :completed %>
  <% end %>
  <%= f.date_field :start_date %>
  <%= f.date_field :due_date %>
  <%= f.collection_check_boxes(:tag_ids, @tags, :id, :title) %>
  <%= f.form_group do %>
    <%= f.submit "Submit"%>
  <% end %>
<% end %>